FROM  amazonlinux:2

WORKDIR /app
COPY . /app

RUN yum install -y pkg-config gcc mkdir which sudo git wget openblas pip make yum-utils

RUN yum install –y python3.8
#RUN amazon-linux-extras install -y python3.8
#RUN sudo ln -s /usr/bin/python3.8 /usr/bin/python3
#RUN python3 -m pip install setuptools wheel numpy netCDF4

#RUN amazon-linux-extras install -y epel
#RUN yum install –y epel-release
#RUN yum-config-manager --enable epel
#RUN yum install -y hdf5-devel

#RUN python3 -m pip install h5py 

#RUN cd /app && \
#    git clone https://github.com/kmaterna/InSAR_CGM_readers_writers.git && \
#    cd InSAR_CGM_readers_writers && \
#    ./setup.py install --user   

CMD [ "/bin/bash" ]
