FROM  amazonlinux
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV UCVM_SRC_PATH=/app/ucvm UCVM_INSTALL_PATH=/usr/local/opt/ucvm 

## on Carina, trying to test out how .bashrc/.bash_profile is used.
## home directory,
#>>>.bash_profile<<<
#
#   ## If .bash_profile exists, bash doesn't read .profile
#   if [[ -f ~/.profile ]]; then
#     . ~/.profile
#   fi
#
#   ## If the shell is interactive and .bashrc exists, get the aliases and functions
#   if [[ $- == *i* && -f ~/.bashrc ]]; then
#     . ~/.bashrc
#   fi
#
#>>>.bashrc<<<
#   echo "*** original mei .bashrc"
#
#   export GOPATH=${HOME}/go
#   export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin
#
#   #ln -s /usr/local/etc/bash_completion.d/singularity /etc/profile.d/singularity.sh
#   #. /usr/local/etc/bash_completion.d/singularity
#
#   export PS1='${HOSTNAME} >'
#   echo "*** mei after set PS1"
#
#   if [[ -f /app/.nbashrc ]]; then
#     echo "*** calling /app/.nbashrc from mei .bashrc"
#     . /app/.nbashrc
#   fi
#

WORKDIR /app
COPY . /app

RUN yum install -y sudo wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrende
r1 mercurial subversion git gcc gcc-gfortran libtool autoconf automake make which tkinter

RUN yum install -y xorg-x11-apps
ENV DISPLAY host.docker.internal:0 

RUN echo "echo 'calling generated bashrc..'"  >> ~/.bashrc

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda2-2019.07-Linux-x86_64.sh -O ~
/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /usr/local/conda && \
    ln -s /usr/local/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /usr/local/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /usr/local/conda/ -follow -type f -name '*.a' -delete && \
    find /usr/local/conda/ -follow -type f -name '*.js.map' -delete && \
    /usr/local/conda/bin/conda clean -afy

## python basemap, basemap-data-hires, matplotlib
RUN /usr/local/conda/bin/conda install -y matplotlib basemap basemap-data-hires

RUN echo "export PS1=\"inContainer >\"" >> ~/.bashrc && \
    cp ~/.bashrc /app/.nbashrc  && \
    echo "echo \">>> after generated bashrc PS1\"" >> ~/.bashrc && \
    echo "echo \">>> after nbashrc PS1\"" >> /app/.nbashrc

CMD [ "/bin/bash" ]

